### ISSUE TITLE
instantlyrics command not found

### ISSUE THREAD

**Issue by raphraph** [sirfoga/Instant-Lyrics#1]
I followed the updated instructions.
System requirements are installed.

I cloned your repository, ran pip install inside the folder, output is following :
`Processing /opt/Instant-Lyrics
Collecting beautifulsoup4 (from Instant-Lyrics==2.0.1)
  Downloading https://files.pythonhosted.org/packages/8b/0e/048a2f88bc4be5e3697df9dc1f7b9d5c9c75be62676feeeb91d2e896c5ea/beautifulsoup4-4.7.1-py2-none-any.whl (94kB)
    100% |████████████████████████████████| 102kB 463kB/s 
Collecting lxml (from Instant-Lyrics==2.0.1)
  Downloading https://files.pythonhosted.org/packages/18/46/9a3298a4db01dc3801c34b314103b0330540da421bffc3a6ec316fa861c2/lxml-4.3.2-cp27-cp27mu-manylinux1_x86_64.whl (5.6MB)
    100% |████████████████████████████████| 5.6MB 226kB/s 
Collecting requests (from Instant-Lyrics==2.0.1)
  Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 2.1MB/s 
Collecting soupsieve>=1.2 (from beautifulsoup4->Instant-Lyrics==2.0.1)
  Downloading https://files.pythonhosted.org/packages/77/78/bca00cc9fa70bba1226ee70a42bf375c4e048fe69066a0d9b5e69bc2a79a/soupsieve-1.8-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 2.1MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests->Instant-Lyrics==2.0.1)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 4.7MB/s 
Collecting idna<2.9,>=2.5 (from requests->Instant-Lyrics==2.0.1)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 3.0MB/s 
Collecting certifi>=2017.4.17 (from requests->Instant-Lyrics==2.0.1)
  Downloading https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl (158kB)
    100% |████████████████████████████████| 163kB 2.0MB/s 
Collecting urllib3<1.25,>=1.21.1 (from requests->Instant-Lyrics==2.0.1)
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
    100% |████████████████████████████████| 122kB 2.2MB/s 
Collecting backports.functools-lru-cache; python_version < "3" (from soupsieve>=1.2->beautifulsoup4->Instant-Lyrics==2.0.1)
  Downloading https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Building wheels for collected packages: Instant-Lyrics
  Running setup.py bdist_wheel for Instant-Lyrics ... done
  Stored in directory: /home/[username]/.cache/pip/wheels/70/ae/0f/c0744bccf60f4b88e7c890e53e87edd1c799814f4a75282186
Successfully built Instant-Lyrics
Installing collected packages: backports.functools-lru-cache, soupsieve, beautifulsoup4, lxml, chardet, idna, certifi, urllib3, requests, Instant-Lyrics
Successfully installed Instant-Lyrics-2.0.1 backports.functools-lru-cache-1.5 beautifulsoup4-4.7.1 certifi-2019.3.9 chardet-3.0.4 idna-2.8 lxml-4.3.2 requests-2.21.0 soupsieve-1.8 urllib3-1.24.1`

Then trying to launch the application with 'instantlyrics' I get a "command not found" message.

**Comment by sirfoga** [comment]
The entry point was created (`Installing collected packages: backports ... requests, Instant-Lyrics Successfully installed Instant-Lyrics-2.0.1`) but somehow you cannot see the binary.

Have you tried with virtualenv?

```bash
git clone https://github.com/sirfoga/Instant-Lyrics
virtualenv -p /usr/bin/python3 --system-site-packages venv
source venv/bin/activate
cd Instant-Lyrics
pip install .
```
then you should be able to call
```bash
instantlyrics  # or venv/bin/instantlyrics
```

**Comment by raphraph** [comment]
Thanks.
Using virtualenv seems to got me further but it is still not working (tried on two computers, both Ubuntu 18.10).

Now running `instantlyrics` I get the following error :

`UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.`

and also a few line below 
```
import urllib.parse as urlparse
ImportError: No module named parse
```
Probably something due to python version compatibility ? but I didn't manage to solve the problem yet.

**Comment by sirfoga** [comment]
> UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.

`pip install soupsieve`

> import urllib.parse as urlparse
ImportError: No module named parse

are you using Python 3? The script is meant to be running under Python 3. Please see [this stackoverflow question](https://stackoverflow.com/a/49336105/7643222) regarding the same issue of yours

**Comment by raphraph** [comment]
I meant that I had the same problem on two different pc's.

Of course I tried to install soupsieve, also uninstall/reinstall, same for some python packages, but it didn't solve the problem.

I had already found the stackoverflow question you linked but to be honest I'm not familiar enough with python to understand exactly what to do (I see that I have both 2.7 and 3 version installed apparently).
Thanks for your help anyway.

**Comment by sirfoga** [comment]
> I see that I have both 2.7 and 3 version installed apparently

You mean in the virtualenv? There should only be the 3 version.

When installing with `pip` and running the script with `python`, are you using the `pip` and the `python` of the virtualenv? (you should `source venv/bin/activate` to do so). Otherwise you're using the system-level `python` and `pip`...

>  I'm not familiar enough with python to understand exactly what to do

Simple: just run the script with 3 version of `python`

**Comment by raphraph** [comment]
Ok thanks I made it work.
I think it was because I didn't understand clearly how virtualenv worked.
